// Mock data for development - Replace with API calls in production

export const mockShops = [
    {
        id: "shop-001",
        name: "ร้านบิวตี้พลัส",
        nameEn: "Beauty Plus Shop",
        address: "123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110",
        phone: "02-123-4567",
        contactPerson: "คุณสมหญิง",
        email: "beautyplus@email.com",
        lastOrder: "2024-12-04",
        totalOrders: 45,
        creditLimit: 500000,
    },
    {
        id: "shop-002",
        name: "ร้านเครื่องสำอางนภา",
        nameEn: "Napha Cosmetics",
        address: "456 ถนนรัชดาภิเษก แขวงดินแดง เขตดินแดง กรุงเทพฯ 10400",
        phone: "02-234-5678",
        contactPerson: "คุณนภา",
        email: "napha.cosmetics@email.com",
        lastOrder: "2024-12-03",
        totalOrders: 32,
        creditLimit: 300000,
    },
    {
        id: "shop-003",
        name: "ร้านกลามัวร์บิวตี้",
        nameEn: "Glamour Beauty",
        address: "789 ถนนพระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10310",
        phone: "02-345-6789",
        contactPerson: "คุณแก้ว",
        email: "glamour.beauty@email.com",
        lastOrder: "2024-12-02",
        totalOrders: 28,
        creditLimit: 400000,
    },
    {
        id: "shop-004",
        name: "ร้านชาร์มมิ่งเลดี้",
        nameEn: "Charming Lady",
        address: "321 ถนนลาดพร้าว แขวงจอมพล เขตจตุจักร กรุงเทพฯ 10900",
        phone: "02-456-7890",
        contactPerson: "คุณมะลิ",
        email: "charming.lady@email.com",
        lastOrder: "2024-12-01",
        totalOrders: 51,
        creditLimit: 600000,
    },
    {
        id: "shop-005",
        name: "ร้านพิ้งค์โรส",
        nameEn: "Pink Rose Shop",
        address: "654 ถนนสีลม แขวงสีลม เขตบางรัก กรุงเทพฯ 10500",
        phone: "02-567-8901",
        contactPerson: "คุณกุหลาบ",
        email: "pinkrose@email.com",
        lastOrder: "2024-11-30",
        totalOrders: 19,
        creditLimit: 250000,
    },
    {
        id: "shop-006",
        name: "ร้านสกินแคร์เฮาส์",
        nameEn: "Skincare House",
        address: "987 ถนนเพชรบุรี แขวงมักกะสัน เขตราชเทวี กรุงเทพฯ 10400",
        phone: "02-678-9012",
        contactPerson: "คุณผิวดี",
        email: "skincare.house@email.com",
        lastOrder: "2024-12-04",
        totalOrders: 67,
        creditLimit: 750000,
    },
    {
        id: "shop-007",
        name: "ร้านเลดี้เฟิร์ส",
        nameEn: "Lady First",
        address: "147 ถนนสาทร แขวงยานนาวา เขตสาทร กรุงเทพฯ 10120",
        phone: "02-789-0123",
        contactPerson: "คุณหญิง",
        email: "ladyfirst@email.com",
        lastOrder: "2024-12-03",
        totalOrders: 38,
        creditLimit: 450000,
    },
    {
        id: "shop-008",
        name: "ร้านบิวตี้ควีน",
        nameEn: "Beauty Queen",
        address: "258 ถนนงามวงศ์วาน แขวงลาดยาว เขตจตุจักร กรุงเทพฯ 10900",
        phone: "02-890-1234",
        contactPerson: "คุณราชินี",
        email: "beauty.queen@email.com",
        lastOrder: "2024-11-28",
        totalOrders: 22,
        creditLimit: 350000,
    },
    {
        id: "shop-009",
        name: "ร้านพรีเมี่ยมบิวตี้",
        nameEn: "Premium Beauty",
        address: "369 ถนนวิภาวดีรังสิต แขวงจอมพล เขตจตุจักร กรุงเทพฯ 10900",
        phone: "02-901-2345",
        contactPerson: "คุณพรีม",
        email: "premium.beauty@email.com",
        lastOrder: "2024-12-04",
        totalOrders: 89,
        creditLimit: 1000000,
    },
    {
        id: "shop-010",
        name: "ร้านเอเวอร์กรีนบิวตี้",
        nameEn: "Evergreen Beauty",
        address: "741 ถนนพหลโยธิน แขวงสามเสนใน เขตพญาไท กรุงเทพฯ 10400",
        phone: "02-012-3456",
        contactPerson: "คุณใบเขียว",
        email: "evergreen@email.com",
        lastOrder: "2024-12-02",
        totalOrders: 41,
        creditLimit: 500000,
    },
];

export const mockProducts = [
    {
        id: "prod-001",
        name: "Velvet Matte Lipstick - Rose Pink",
        sku: "LIP-VM-001",
        category: "Lipstick",
        price: 450,
        stock: 150,
        minStock: 50,
        image: "/products/lipstick-rose.jpg",
    },
    {
        id: "prod-002",
        name: "Velvet Matte Lipstick - Coral Red",
        sku: "LIP-VM-002",
        category: "Lipstick",
        price: 450,
        stock: 85,
        minStock: 50,
        image: "/products/lipstick-coral.jpg",
    },
    {
        id: "prod-003",
        name: "HD Foundation - Ivory",
        sku: "FND-HD-001",
        category: "Foundation",
        price: 890,
        stock: 120,
        minStock: 40,
        image: "/products/foundation-ivory.jpg",
    },
    {
        id: "prod-004",
        name: "HD Foundation - Natural Beige",
        sku: "FND-HD-002",
        category: "Foundation",
        price: 890,
        stock: 95,
        minStock: 40,
        image: "/products/foundation-beige.jpg",
    },
    {
        id: "prod-005",
        name: "HD Foundation - Sand",
        sku: "FND-HD-003",
        category: "Foundation",
        price: 890,
        stock: 78,
        minStock: 40,
        image: "/products/foundation-sand.jpg",
    },
    {
        id: "prod-006",
        name: "Volume Mascara - Black",
        sku: "MAS-VL-001",
        category: "Mascara",
        price: 350,
        stock: 200,
        minStock: 60,
        image: "/products/mascara-black.jpg",
    },
    {
        id: "prod-007",
        name: "Waterproof Mascara - Black",
        sku: "MAS-WP-001",
        category: "Mascara",
        price: 390,
        stock: 15,
        minStock: 50,
        image: "/products/mascara-wp.jpg",
    },
    {
        id: "prod-008",
        name: "Eye Shadow Palette - Nude",
        sku: "EYE-PL-001",
        category: "Eye Shadow",
        price: 650,
        stock: 45,
        minStock: 30,
        image: "/products/eyeshadow-nude.jpg",
    },
    {
        id: "prod-009",
        name: "Eye Shadow Palette - Smoky",
        sku: "EYE-PL-002",
        category: "Eye Shadow",
        price: 650,
        stock: 38,
        minStock: 30,
        image: "/products/eyeshadow-smoky.jpg",
    },
    {
        id: "prod-010",
        name: "Brow Pencil - Dark Brown",
        sku: "BRW-PC-001",
        category: "Eyebrow",
        price: 280,
        stock: 180,
        minStock: 70,
        image: "/products/brow-dark.jpg",
    },
    {
        id: "prod-011",
        name: "Brow Pencil - Light Brown",
        sku: "BRW-PC-002",
        category: "Eyebrow",
        price: 280,
        stock: 165,
        minStock: 70,
        image: "/products/brow-light.jpg",
    },
    {
        id: "prod-012",
        name: "Setting Powder - Translucent",
        sku: "PWD-ST-001",
        category: "Powder",
        price: 520,
        stock: 8,
        minStock: 35,
        image: "/products/powder-translucent.jpg",
    },
    {
        id: "prod-013",
        name: "Blush - Peach Glow",
        sku: "BLS-PG-001",
        category: "Blush",
        price: 380,
        stock: 92,
        minStock: 40,
        image: "/products/blush-peach.jpg",
    },
    {
        id: "prod-014",
        name: "Blush - Berry Kiss",
        sku: "BLS-BK-001",
        category: "Blush",
        price: 380,
        stock: 67,
        minStock: 40,
        image: "/products/blush-berry.jpg",
    },
    {
        id: "prod-015",
        name: "Highlighter - Gold Shimmer",
        sku: "HLT-GS-001",
        category: "Highlighter",
        price: 420,
        stock: 55,
        minStock: 25,
        image: "/products/highlighter-gold.jpg",
    },
    {
        id: "prod-016",
        name: "Lip Gloss - Clear Shine",
        sku: "GLO-CS-001",
        category: "Lip Gloss",
        price: 290,
        stock: 3,
        minStock: 45,
        image: "/products/gloss-clear.jpg",
    },
    {
        id: "prod-017",
        name: "Lip Gloss - Pink Shimmer",
        sku: "GLO-PS-001",
        category: "Lip Gloss",
        price: 290,
        stock: 112,
        minStock: 45,
        image: "/products/gloss-pink.jpg",
    },
    {
        id: "prod-018",
        name: "Makeup Primer - Hydrating",
        sku: "PRM-HY-001",
        category: "Primer",
        price: 580,
        stock: 72,
        minStock: 30,
        image: "/products/primer-hydrating.jpg",
    },
    {
        id: "prod-019",
        name: "Makeup Primer - Mattifying",
        sku: "PRM-MT-001",
        category: "Primer",
        price: 580,
        stock: 58,
        minStock: 30,
        image: "/products/primer-matte.jpg",
    },
    {
        id: "prod-020",
        name: "Setting Spray - Long Lasting",
        sku: "SPR-LL-001",
        category: "Setting Spray",
        price: 490,
        stock: 5,
        minStock: 40,
        image: "/products/setting-spray.jpg",
    },
];

export const mockOrders = [
    {
        id: "ORD-2024-001",
        shopId: "shop-001",
        shopName: "ร้านบิวตี้พลัส",
        salespersonId: "user-001",
        salespersonName: "Sarah Johnson",
        status: "completed",
        orderDate: "2024-12-04T10:30:00",
        deliveryDate: "2024-12-05",
        items: [
            { productId: "prod-001", productName: "Velvet Matte Lipstick - Rose Pink", quantity: 24, unitPrice: 450, total: 10800 },
            { productId: "prod-003", productName: "HD Foundation - Ivory", quantity: 12, unitPrice: 890, total: 10680 },
            { productId: "prod-006", productName: "Volume Mascara - Black", quantity: 36, unitPrice: 350, total: 12600 },
        ],
        subtotal: 34080,
        discount: 3408,
        discountPercent: 10,
        total: 30672,
        paymentStatus: "paid",
        notes: "Regular monthly order",
    },
    {
        id: "ORD-2024-002",
        shopId: "shop-003",
        shopName: "ร้านกลามัวร์บิวตี้",
        salespersonId: "user-002",
        salespersonName: "John Doe",
        status: "pending",
        orderDate: "2024-12-04T14:15:00",
        deliveryDate: "2024-12-06",
        items: [
            { productId: "prod-008", productName: "Eye Shadow Palette - Nude", quantity: 18, unitPrice: 650, total: 11700 },
            { productId: "prod-013", productName: "Blush - Peach Glow", quantity: 24, unitPrice: 380, total: 9120 },
            { productId: "prod-015", productName: "Highlighter - Gold Shimmer", quantity: 12, unitPrice: 420, total: 5040 },
        ],
        subtotal: 25860,
        discount: 0,
        discountPercent: 0,
        total: 25860,
        paymentStatus: "pending",
        notes: "",
    },
    {
        id: "ORD-2024-003",
        shopId: "shop-006",
        shopName: "ร้านสกินแคร์เฮาส์",
        salespersonId: "user-001",
        salespersonName: "Sarah Johnson",
        status: "processing",
        orderDate: "2024-12-03T09:45:00",
        deliveryDate: "2024-12-05",
        items: [
            { productId: "prod-018", productName: "Makeup Primer - Hydrating", quantity: 30, unitPrice: 580, total: 17400 },
            { productId: "prod-019", productName: "Makeup Primer - Mattifying", quantity: 30, unitPrice: 580, total: 17400 },
            { productId: "prod-020", productName: "Setting Spray - Long Lasting", quantity: 48, unitPrice: 490, total: 23520 },
            { productId: "prod-012", productName: "Setting Powder - Translucent", quantity: 24, unitPrice: 520, total: 12480 },
        ],
        subtotal: 70800,
        discount: 7080,
        discountPercent: 10,
        total: 63720,
        paymentStatus: "partial",
        notes: "Large order - 50% advance payment received",
    },
    {
        id: "ORD-2024-004",
        shopId: "shop-009",
        shopName: "ร้านพรีเมี่ยมบิวตี้",
        salespersonId: "user-003",
        salespersonName: "Mike Wilson",
        status: "completed",
        orderDate: "2024-12-02T16:20:00",
        deliveryDate: "2024-12-03",
        items: [
            { productId: "prod-002", productName: "Velvet Matte Lipstick - Coral Red", quantity: 48, unitPrice: 450, total: 21600 },
            { productId: "prod-004", productName: "HD Foundation - Natural Beige", quantity: 36, unitPrice: 890, total: 32040 },
            { productId: "prod-010", productName: "Brow Pencil - Dark Brown", quantity: 60, unitPrice: 280, total: 16800 },
            { productId: "prod-011", productName: "Brow Pencil - Light Brown", quantity: 60, unitPrice: 280, total: 16800 },
        ],
        subtotal: 87240,
        discount: 13086,
        discountPercent: 15,
        total: 74154,
        paymentStatus: "paid",
        notes: "Premium customer - 15% discount applied",
    },
    {
        id: "ORD-2024-005",
        shopId: "shop-004",
        shopName: "ร้านชาร์มมิ่งเลดี้",
        salespersonId: "user-002",
        salespersonName: "John Doe",
        status: "cancelled",
        orderDate: "2024-12-01T11:00:00",
        deliveryDate: null,
        items: [
            { productId: "prod-007", productName: "Waterproof Mascara - Black", quantity: 24, unitPrice: 390, total: 9360 },
            { productId: "prod-016", productName: "Lip Gloss - Clear Shine", quantity: 36, unitPrice: 290, total: 10440 },
        ],
        subtotal: 19800,
        discount: 0,
        discountPercent: 0,
        total: 19800,
        paymentStatus: "refunded",
        notes: "Cancelled by customer - out of stock items",
    },
];

// Helper functions
export const getShopById = (id: string) => mockShops.find((shop) => shop.id === id);
export const getProductById = (id: string) => mockProducts.find((product) => product.id === id);
export const getOrderById = (id: string) => mockOrders.find((order) => order.id === id);

export const getLowStockProducts = (threshold?: number) =>
    mockProducts.filter((product) => product.stock <= (threshold ?? product.minStock));

export const getOrdersByStatus = (status: string) =>
    mockOrders.filter((order) => order.status === status);

export const getOrdersByShop = (shopId: string) =>
    mockOrders.filter((order) => order.shopId === shopId);

export const getOrdersBySalesperson = (salespersonId: string) =>
    mockOrders.filter((order) => order.salespersonId === salespersonId);

// Product categories for filtering
export const productCategories = [
    "Lipstick",
    "Foundation",
    "Mascara",
    "Eye Shadow",
    "Eyebrow",
    "Powder",
    "Blush",
    "Highlighter",
    "Lip Gloss",
    "Primer",
    "Setting Spray",
];

// Order status options
export const orderStatuses = [
    { value: "pending", label: "Pending", color: "yellow" },
    { value: "processing", label: "Processing", color: "blue" },
    { value: "completed", label: "Completed", color: "green" },
    { value: "cancelled", label: "Cancelled", color: "red" },
];

// Payment status options
export const paymentStatuses = [
    { value: "pending", label: "Pending", color: "yellow" },
    { value: "partial", label: "Partial", color: "blue" },
    { value: "paid", label: "Paid", color: "green" },
    { value: "refunded", label: "Refunded", color: "gray" },
];
